# Generated by Django 4.1.7 on 2023-05-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personas', '0005_rename_facebook_alumno_facebook'),
        ('gestion_cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_personas.tutor'),
            preserve_default=False,
        ),
    ]
