# Generated by Django 4.1.7 on 2023-03-29 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_cursos', '0001_initial'),
        ('gestion_personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_personas.alumno'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cursos.categoria'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cursos.curso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_personas.alumno'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cursos.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_cursos.categoria'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_personas.docente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='inscriptos',
            field=models.ManyToManyField(through='gestion_cursos.Inscripcion', to='gestion_personas.alumno'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_personas.tutor'),
        ),
    ]
