# Generated by Django 4.1.7 on 2023-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cursos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='curso',
            name='photo',
            field=models.ImageField(default=-1.0, upload_to='image'),
            preserve_default=False,
        ),
    ]
