# Generated by Django 4.1.7 on 2023-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cursos', '0003_solicitudinscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudinscripcion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='solicitudinscripcion',
            name='estado',
            field=models.CharField(choices=[('S', 'Solicitado'), ('A', 'Aceptado'), ('R', 'Rechazado'), ('P', 'Pendiente')], default='S', max_length=1),
        ),
    ]
