# Generated by Django 4.1.7 on 2023-04-03 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cursos', '0003_remove_curso_fecha_creacion_curso_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
