# Generated by Django 4.1.7 on 2023-04-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cursos', '0004_curso_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='tutor',
        ),
    ]
