# Generated by Django 4.1.7 on 2023-05-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cursos', '0004_remove_solicitudinscripcion_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='aceptado',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('S', 'Solicitado'), ('A', 'Aceptado'), ('R', 'Rechazado'), ('P', 'Pendiente')], default='S', max_length=1),
        ),
    ]
