# Generated by Django 4.1.7 on 2023-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cursos', '0005_remove_curso_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='photo',
            field=models.ImageField(upload_to="static 'assets/img/"),
        ),
    ]
