# Generated by Django 4.1.7 on 2023-04-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cursos', '0008_alter_curso_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='photo',
            field=models.ImageField(default=-1.0, upload_to='categorias'),
            preserve_default=False,
        ),
    ]
