# Generated by Django 4.1.7 on 2023-04-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='rol',
            field=models.CharField(default='alumno', max_length=50),
        ),
        migrations.AddField(
            model_name='docente',
            name='rol',
            field=models.CharField(default='docente', max_length=50),
        ),
        migrations.AddField(
            model_name='ingresopersona',
            name='rol',
            field=models.CharField(default='ingresoPersona', max_length=50),
        ),
        migrations.AddField(
            model_name='inscripto',
            name='rol',
            field=models.CharField(default='inscripto', max_length=50),
        ),
        migrations.AddField(
            model_name='tutor',
            name='rol',
            field=models.CharField(default='tutor', max_length=50),
        ),
    ]
