# Generated by Django 4.1.7 on 2023-04-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='photo',
            field=models.ImageField(default=-1.0, upload_to='alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='photo',
            field=models.ImageField(default=-1.0, upload_to='docentes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='photo',
            field=models.ImageField(default=-1.0, upload_to='tutor'),
            preserve_default=False,
        ),
    ]
