# Generated by Django 4.1.7 on 2023-04-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personas', '0003_alumno_facebook_alumno_about_alumno_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='firstName',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='company',
            new_name='donde',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='lastName',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='country',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='job',
            new_name='que',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='phone',
            new_name='telefono',
        ),
    ]
