# Generated by Django 4.1.7 on 2023-04-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_personas', '0004_rename_firstname_alumno_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Facebook',
            new_name='facebook',
        ),
    ]
